### PR TITLE
Algorithim & digits support

### LINKED ISSUE #287: Support digits paramter
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>
<You can also open an issue by Tweeting with #AuthenticatorFeedback>

### LINKED ISSUE #380: Support algorithm paramater
**Describe the bug:** The codes generated by Authenticator for the settings URL posted below are not being accepted by a website

**Platform:** 
 - Browser: Firefox
 - Browser Version: 68.0.2 x64

The settings URL: otpauth://totp/IconParc:viktor@*anonymized*?REMOVED&algorithm=SHA512&digits=6

The site to accept it is not publicly accessible, but comparison with another generator should enable code testing.

Thank you for looking into this!
Viktor

### PR DESCRIPTION
**Pull request by mymindstorm**
closes #380 and #287

### CODE REVIEW

File: src/background.ts [hunk 1]
```diff
@@ -163,6 +165,11 @@ async function getTotp(text: string) {
             isNaN(period) || period < 0 || period > 60 || 60 % period !== 0
               ? undefined
               : period;
+        } else if (parameter[0].toLowerCase() === "digits") {
+          digits = Number(parameter[1]);
+          digits = isNaN(digits) ? 6 : digits;
```
Comment (Sneezry) [inline src/background.ts]: If parameter[0] is empty string, digits equals to zero here.

File: src/components/Popup/AddAccountPage.vue [hunk 2]
```diff
@@ -16,6 +16,19 @@
         v-model.number="newAccount.period"
         v-bind:disabled="newAccount.type === OTPType.hotp"
       />
+      <label class="combo-label">{{ i18n.digits }}</label>
+      <select v-model="newAccount.digits">
+        <option v-bind:value="6">6</option>
```
Comment (Sneezry) [inline src/components/Popup/AddAccountPage.vue]: Why not use `value` directly here, it seems we needn't change options value later.

**Review by Sneezry — APPROVED** [review]
