### PR TITLE
Fix 3rd party backup errors

### LINKED ISSUE #659: Importing data does not work
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** When I import my data from the extension, it doesn't work. I tired importing the JSON file and the text file from my previous backup, when I clicked the button nothing happened. No warning, no progress, nothing. I tired reinstalling the extension to no avail.

**Platform:** <This is required>
 - Browser: Edge
 - Browser Version: Version 90.0.818.56 (Official build) (64-bit)

### PR DESCRIPTION
**Pull request by mymindstorm**
fixes #659

### CODE REVIEW

File: src/components/Import/FileImport.vue [hunk 1]
```diff
@@ -75,8 +76,10 @@ export default Vue.extend({
 
           let key: { enc: string; hash: string } | null = null;
 
-          if (importData.key) {
-            key = importData.key;
+          if (importData.hasOwnProperty("key")) {
```
Comment (Sneezry) [inline src/components/Import/FileImport.vue:79]: Is it necessary? `importData` is parsed from a JSON string, and not an instance of a class. `importData` has no inheritance from the prototype.

Comment (mymindstorm) [reply src/components/Import/FileImport.vue:79]: Yes, the error with backup creates data like this:
```json
{
    "key": null
}
```
Because of that
```js
Boolean(importData.key) == false
```
so the only way to check if the key exists if it could be null is:
```js
importData.hasOwnProperty("key")
// or
"key" in importData
```
I am not aware of any relation between hasOwnProperty and classes, I am under the impression that it is a method for objects.

Comment (Sneezry) [reply src/components/Import/FileImport.vue:79]: I see.

**Review by Sneezry — APPROVED** [review]
